/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as BellyBindingRouteImport } from './routes/belly-binding'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HearthRouteImport } from './routes/hearth'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NouriRouteImport } from './routes/nouri'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminBusinessRouteImport } from './routes/admin/business'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminLandingRouteImport } from './routes/admin/landing'
import { Route as AdminLaunchRouteImport } from './routes/admin/launch'
import { Route as AdminNouriRouteImport } from './routes/admin/nouri'
import { Route as AdminPreviewRouteImport } from './routes/admin/preview'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAppointmentsRouteImport } from './routes/app/appointments'
import { Route as AppBindingRouteImport } from './routes/app/binding'
import { Route as AppGroceryRouteImport } from './routes/app/grocery'
import { Route as AppJourneyRouteImport } from './routes/app/journey'
import { Route as AppMealsRouteImport } from './routes/app/meals'
import { Route as AppMoveRouteImport } from './routes/app/move'
import { Route as AppNouriRouteImport } from './routes/app/nouri'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppPantryRouteImport } from './routes/app/pantry'
import { Route as AppPartnerRouteImport } from './routes/app/partner'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppResourcesRouteImport } from './routes/app/resources'
import { Route as AppStoreRouteImport } from './routes/app/store'
import { Route as AdminClientsUserIdRouteImport } from './routes/admin/clients.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BellyBindingRoute = BellyBindingRouteImport.update({
  id: '/belly-binding',
  path: '/belly-binding',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HearthRoute = HearthRouteImport.update({
  id: '/hearth',
  path: '/hearth',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NouriRoute = NouriRouteImport.update({
  id: '/nouri',
  path: '/nouri',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessRoute = AdminBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingRoute = AdminLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaunchRoute = AdminLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNouriRoute = AdminNouriRouteImport.update({
  id: '/nouri',
  path: '/nouri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppBindingRoute = AppBindingRouteImport.update({
  id: '/binding',
  path: '/binding',
  getParentRoute: () => AppRoute,
} as any)
const AppGroceryRoute = AppGroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppMoveRoute = AppMoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => AppRoute,
} as any)
const AppNouriRoute = AppNouriRouteImport.update({
  id: '/nouri',
  path: '/nouri',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnerRoute = AppPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AdminClientsUserIdRoute = AdminClientsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminClientsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/belly-binding': typeof BellyBindingRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/hearth': typeof HearthRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/nouri': typeof NouriRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/nouri': typeof AdminNouriRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/binding': typeof AppBindingRoute
  '/app/grocery': typeof AppGroceryRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/meals': typeof AppMealsRoute
  '/app/move': typeof AppMoveRoute
  '/app/nouri': typeof AppNouriRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/partner': typeof AppPartnerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/store': typeof AppStoreRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/belly-binding': typeof BellyBindingRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/hearth': typeof HearthRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/nouri': typeof NouriRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/nouri': typeof AdminNouriRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/binding': typeof AppBindingRoute
  '/app/grocery': typeof AppGroceryRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/meals': typeof AppMealsRoute
  '/app/move': typeof AppMoveRoute
  '/app/nouri': typeof AppNouriRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/partner': typeof AppPartnerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/store': typeof AppStoreRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/belly-binding': typeof BellyBindingRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/hearth': typeof HearthRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/nouri': typeof NouriRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/nouri': typeof AdminNouriRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/binding': typeof AppBindingRoute
  '/app/grocery': typeof AppGroceryRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/meals': typeof AppMealsRoute
  '/app/move': typeof AppMoveRoute
  '/app/nouri': typeof AppNouriRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pantry': typeof AppPantryRoute
  '/app/partner': typeof AppPartnerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/store': typeof AppStoreRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/belly-binding'
    | '/checkout'
    | '/contact'
    | '/hearth'
    | '/join'
    | '/login'
    | '/nouri'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/business'
    | '/admin/calendar'
    | '/admin/clients'
    | '/admin/content'
    | '/admin/landing'
    | '/admin/launch'
    | '/admin/nouri'
    | '/admin/preview'
    | '/admin/setup'
    | '/app/appointments'
    | '/app/binding'
    | '/app/grocery'
    | '/app/journey'
    | '/app/meals'
    | '/app/move'
    | '/app/nouri'
    | '/app/onboarding'
    | '/app/pantry'
    | '/app/partner'
    | '/app/profile'
    | '/app/resources'
    | '/app/store'
    | '/admin/'
    | '/app/'
    | '/admin/clients/$userId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/belly-binding'
    | '/checkout'
    | '/contact'
    | '/hearth'
    | '/join'
    | '/login'
    | '/nouri'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/business'
    | '/admin/calendar'
    | '/admin/clients'
    | '/admin/content'
    | '/admin/landing'
    | '/admin/launch'
    | '/admin/nouri'
    | '/admin/preview'
    | '/admin/setup'
    | '/app/appointments'
    | '/app/binding'
    | '/app/grocery'
    | '/app/journey'
    | '/app/meals'
    | '/app/move'
    | '/app/nouri'
    | '/app/onboarding'
    | '/app/pantry'
    | '/app/partner'
    | '/app/profile'
    | '/app/resources'
    | '/app/store'
    | '/admin'
    | '/app'
    | '/admin/clients/$userId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/belly-binding'
    | '/checkout'
    | '/contact'
    | '/hearth'
    | '/join'
    | '/login'
    | '/nouri'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/business'
    | '/admin/calendar'
    | '/admin/clients'
    | '/admin/content'
    | '/admin/landing'
    | '/admin/launch'
    | '/admin/nouri'
    | '/admin/preview'
    | '/admin/setup'
    | '/app/appointments'
    | '/app/binding'
    | '/app/grocery'
    | '/app/journey'
    | '/app/meals'
    | '/app/move'
    | '/app/nouri'
    | '/app/onboarding'
    | '/app/pantry'
    | '/app/partner'
    | '/app/profile'
    | '/app/resources'
    | '/app/store'
    | '/admin/'
    | '/app/'
    | '/admin/clients/$userId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  BellyBindingRoute: typeof BellyBindingRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HearthRoute: typeof HearthRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  NouriRoute: typeof NouriRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belly-binding': {
      id: '/belly-binding'
      path: '/belly-binding'
      fullPath: '/belly-binding'
      preLoaderRoute: typeof BellyBindingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearth': {
      id: '/hearth'
      path: '/hearth'
      fullPath: '/hearth'
      preLoaderRoute: typeof HearthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouri': {
      id: '/nouri'
      path: '/nouri'
      fullPath: '/nouri'
      preLoaderRoute: typeof NouriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business': {
      id: '/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AdminBusinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing': {
      id: '/admin/landing'
      path: '/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AdminLandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/launch': {
      id: '/admin/launch'
      path: '/launch'
      fullPath: '/admin/launch'
      preLoaderRoute: typeof AdminLaunchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nouri': {
      id: '/admin/nouri'
      path: '/nouri'
      fullPath: '/admin/nouri'
      preLoaderRoute: typeof AdminNouriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview': {
      id: '/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/binding': {
      id: '/app/binding'
      path: '/binding'
      fullPath: '/app/binding'
      preLoaderRoute: typeof AppBindingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grocery': {
      id: '/app/grocery'
      path: '/grocery'
      fullPath: '/app/grocery'
      preLoaderRoute: typeof AppGroceryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey': {
      id: '/app/journey'
      path: '/journey'
      fullPath: '/app/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meals': {
      id: '/app/meals'
      path: '/meals'
      fullPath: '/app/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/move': {
      id: '/app/move'
      path: '/move'
      fullPath: '/app/move'
      preLoaderRoute: typeof AppMoveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nouri': {
      id: '/app/nouri'
      path: '/nouri'
      fullPath: '/app/nouri'
      preLoaderRoute: typeof AppNouriRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pantry': {
      id: '/app/pantry'
      path: '/pantry'
      fullPath: '/app/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/partner': {
      id: '/app/partner'
      path: '/partner'
      fullPath: '/app/partner'
      preLoaderRoute: typeof AppPartnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/clients/$userId': {
      id: '/admin/clients/$userId'
      path: '/$userId'
      fullPath: '/admin/clients/$userId'
      preLoaderRoute: typeof AdminClientsUserIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminClientsRouteChildren {
  AdminClientsUserIdRoute: typeof AdminClientsUserIdRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsUserIdRoute: AdminClientsUserIdRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBusinessRoute: typeof AdminBusinessRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminContentRoute: typeof AdminContentRoute
  AdminLandingRoute: typeof AdminLandingRoute
  AdminLaunchRoute: typeof AdminLaunchRoute
  AdminNouriRoute: typeof AdminNouriRoute
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBusinessRoute: AdminBusinessRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminContentRoute: AdminContentRoute,
  AdminLandingRoute: AdminLandingRoute,
  AdminLaunchRoute: AdminLaunchRoute,
  AdminNouriRoute: AdminNouriRoute,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppBindingRoute: typeof AppBindingRoute
  AppGroceryRoute: typeof AppGroceryRoute
  AppJourneyRoute: typeof AppJourneyRoute
  AppMealsRoute: typeof AppMealsRoute
  AppMoveRoute: typeof AppMoveRoute
  AppNouriRoute: typeof AppNouriRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPantryRoute: typeof AppPantryRoute
  AppPartnerRoute: typeof AppPartnerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppStoreRoute: typeof AppStoreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppBindingRoute: AppBindingRoute,
  AppGroceryRoute: AppGroceryRoute,
  AppJourneyRoute: AppJourneyRoute,
  AppMealsRoute: AppMealsRoute,
  AppMoveRoute: AppMoveRoute,
  AppNouriRoute: AppNouriRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPantryRoute: AppPantryRoute,
  AppPartnerRoute: AppPartnerRoute,
  AppProfileRoute: AppProfileRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppStoreRoute: AppStoreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  BellyBindingRoute: BellyBindingRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HearthRoute: HearthRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  NouriRoute: NouriRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
